name: "Fritz Mesh Dev"
description: "FritzMesh - Development playground"
version: "0.1.0"
slug: "fritzmesh_dev"
init: false
ingress: true
panel_title: Network
panel_icon: mdi:lan
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  Fritzbox username: ""
  Fritzbox password: ""
  fritzbox host:     "fritz.box"
schema:
  Fritzbox username: str
  Fritzbox password: str
  fritzbox host:     str
